FROM julia

RUN apt-get update
RUN sh -c 'echo "deb http://cran.rstudio.com/bin/linux/debian jessie-cran34/" >> /etc/apt/sources.list'
RUN apt-get install dirmngr & apt-key adv --keyserver keys.gnupg.net --recv-key 'FCAE2A0E115C3D8A'
RUN apt-get update && apt-get install -y build-essential ed sed
RUN apt-get install -y unzip curl openssl libssl-dev libcurl4-openssl-dev git python-pip libfreetype6-dev pkg-config python-dev autopoint gettext gettext-base libasprintf-dev libasprintf0c2 libcroco3 libgettextpo-dev libgettextpo0 libunistring0 gettext-doc
RUN apt-get install --force-yes -y r-base-core r-recommended r-base r-base-dev

ADD packages.R packages.R
ADD requirements.txt requirements.txt
ADD packages.sh packages.sh

RUN Rscript packages.R
RUN pip install matplotlib
RUN sh packages.sh

#RUN echo "export LC_ALL=en_US.UTF-8 \n export LANG=en_US.UTF-8 \n export LANGUAGE=en_US.UTF-8" >> /.bashrc
RUN echo 'es_MX.UTF-8 UTF-8' >> /etc/locale.gen
RUN echo 'export es_MX.UTF-8 UTF-8' >> /.bashrc
RUN echo 'LANG=es_ES.UTF-8' >> /etc/locale.conf
RUN echo 'export LANG=es_ES.UTF-8' >> /.bashrc
RUN exec $SHELL

ADD wait-for-it.sh /
RUN chmod +x /wait-for-it.sh

COPY src/ /src/

CMD ["/src/execute.sh"]
