using Plots
plotlyjs()
global_cc = readdlm("../data/clustering/global_cc.csv",',')
pri_cc = readdlm("../data/clustering/pri_cc.csv",',')
prd_cc = readdlm("../data/clustering/prd_cc.csv",',')
pan_cc = readdlm("../data/clustering/pan_cc.csv",',')
independiente_cc = readdlm("../data/clustering/independiente_cc.csv",',')
pt_cc = readdlm("../data/clustering/pt_cc.csv",',')
pvem_cc = readdlm("../data/clustering/pvem_cc.csv",',')
cc = hcat(global_cc,pri_cc,prd_cc,pan_cc,independiente_cc,pt_cc,pvem_cc)
time = collect(1:length(pri_cc))
x = time; y = cc
plotlyjs()
plot(x,global_cc,lab="Global",xaxis=("Tiempo"),yaxis=("Clustering Coefficient",(0,1),0:0.1:1))
plot!(x,pri_cc,lab="PRI")
plot!(x,prd_cc,lab="PRD")
plot!(x,pan_cc,lab="PAN")
plot!(x,independiente_cc,lab="IND")
plot!(x,pt_cc,lab="PT")
plot!(x,pvem_cc,lab="PVEM")
title!("Clustering Coefficient Global vs PVEM")
gui()
