version: "3"

services:
    neo4j:
        build:
            dockerfile: Dockerfile.db
            context: ../DB
        image: ollin18/senate_neo:0.1
        container_name: senate_db
        depends_on: scraper
        environment:
            - NEO4J_AUTH=none
        ports:
            - "7474:7474"
            - "7687:7687"
        networks:
            - senate_net

    scraper:
        build:
            dockerfile: Dockerfile.scrap
            context: ../Scraping
        image: ollin18/scraper:0.1
        container_name: senate_scrap
        volumes:
            - type: volume
            - source: data
              target: /data
        networks:
            - senate_net

networks:
    senate_net:
        external: true
